### ISSUE TITLE
Not work by json format in items

### ISSUE THREAD

**Issue by MohsenEs** [ramon82/zuck.js#101]
["riverscuomo", "photo", 10, "https://raw.githubusercontent.com/ramon82/assets/master/zuck.js/stories/9.jpg", "https://raw.githubusercontent.com/ramon82/assets/master/zuck.js/stories/9.jpg", '', false, false, timestamp()]

its work

 {id:"riverscuomo", type:"photo", length:10, ...}

its not work

**Comment by ramon82** [comment]
You shouldn't use the helpers function in this case.
