### ISSUE TITLE
How to Use it with VueJS Project

### ISSUE THREAD

**Issue by kartikcool15** [ramon82/zuck.js#112]
I want to use these stories with my vuejs Project, How can i go ahead ?

**Comment by NikosEfthias** [comment]
I have the same issue with react its impossible to import and use it says zuck is not a constructor

**Comment by sulaimanwebdev** [comment]
I hope it works with Vue JS

**Comment by ramon82** [comment]
@NikosEfthias you're trying to use npm "zuck" package instead of "zuck.js"

**Comment by mhmdunl1** [comment]
Use cdn in index.html: 

`<link rel="stylesheet" href="https://unpkg.com/zuck.js/dist/zuck.css" />
    <link
      rel="stylesheet"
      href="https://unpkg.com/zuck.js/dist/skins/snapgram.css"
    />
     <script src="https://unpkg.com/zuck.js/dist/zuck.js"></script>
    `
