### ISSUE TITLE
how to add new options, ex: like buttun ...

### ISSUE THREAD

**Issue by imanpr** [ramon82/zuck.js#113]
how can i add like button and show view count to stories?
thanks

**Comment by Benpaul320** [comment]
Please, am looking for the same answer to this question

**Comment by Benpaul320** [comment]
I manipulated everything to add comments and reactions.. i could share.

**Comment by ramon82** [comment]
See #117

**Comment by promise24o** [comment]
> ents an

Please i will like you to share.
