### ISSUE TITLE
Story disappeared on press of space

### ISSUE THREAD

**Issue by anooppassi66** [ramon82/zuck.js#114]
Hello , whenever the space key is pressed the story got disappear. i want to not be disappeared.

**Comment by mayurc137** [comment]
Pressing space, the plugin skips the current story, if you are just using one story it should close the window. 

As of now, the plugin doesn't have any config to turn off this feature. You will have to edit the code yourself. 

Here is the link to link you will have to comment -> 
https://github.com/ramon82/zuck.js/blob/5a190771e57a7b0c1074392736624dd78315ebfa/src/zuck.js#L439

Hope this helps!

**Comment by Benpaul320** [comment]
Yes. thanks
