### ISSUE TITLE
Infinite loop of story on modal / Navigate previous & back

### ISSUE THREAD

**Issue by nashvinxtn** [ramon82/zuck.js#119]
Is there a quick fix to be able to have a loop in the modal slider & also navigate between main stories in the modal. I wanted to make the slider in the modal functions like a coverflow plugin.
![coverflow](https://user-images.githubusercontent.com/11077268/122007520-0e7b1500-cdc9-11eb-9866-7d7365196621.jpg)

**Comment by ramon82** [comment]
this library doesn't do what you're looking for and I have no plans to add it
