### ISSUE TITLE
Story plays before media is ready (eg video)

### ISSUE THREAD

**Issue by lachlanphillips** [ramon82/zuck.js#122]
As the title says, the story will start playing as a blank screen while the video media loads - and then when it loads it will assume it's already played n seconds, and subsequently stop playing when it thinks it has finished the time.

I would love to try and fix this myself, but the code is zuck.js that called another file called zuck.js, only it doesn't actually call that file, but evals a minified copy of that file inline. Very hard to contribute.

**Comment by ramon82** [comment]
See #107
