### ISSUE TITLE
Video and time bugs

### ISSUE THREAD

**Issue by stivoox** [ramon82/zuck.js#13]
Why the video stories doesn't work on mobile ? and why we see those numbers instead of time ?

**Comment by ramon82** [comment]
Hi stivoox, 

Video stories doesn't autoplay on mobile because of browser limitations, and the numbers was a bug which now is fixed :)

**Comment by stivoox** [comment]
Tnx for your update but now any unix timestamp return 18/1/1970

**Comment by ramon82** [comment]
Just changed the time format and forgot it was unix timestamp hahaha. Updated now 👍
