### ISSUE TITLE
Open story modal by default or by clicking a button

### ISSUE THREAD

**Issue by khanfas47** [ramon82/zuck.js#17]
Hi, 
1 - Is there any option to open story modal on page loads without clicking story item?
2- Is there any option to open story modal by clicking a button which will open first story item?
thanks

**Comment by ramon82** [comment]
Hi,

Currently there's no option to do both, since the timeline is generated by the script.

**Comment by suleymangezsat** [comment]
Even if the timeline is generated by the script I think there might be an option to have an input that indicates whether the modal will be opened on page load or on click on avatar.
