### ISSUE TITLE
custom viewer template to add title/text

### ISSUE THREAD

**Issue by dhirajbajaj** [ramon82/zuck.js#18]
Ramon, Great work with the library. 
Is there a way to make a text only post or be able to make custom template viewer like adding title and description with a background image maybe.

**Comment by ramon82** [comment]
Hi Dhiraj,

Currently there's no method to add custom markup into the stories, since the script manage the "story timer" too. It may be added on future versions :)

Thanks!

**Comment by matteodem** [comment]
We would need that for our code.

Any guidance on how we could achieve that right now? 

I assume that the code here needs some adjustment https://github.com/ramon82/zuck.js/blob/master/src/zuck.js#L493
