### ISSUE TITLE
stories.remove(storyId) not defined

### ISSUE THREAD

**Issue by nalsut** [ramon82/zuck.js#19]
This is throwing exception. remove() is not defined as a method

**Comment by nalsut** [comment]
In anycase, I fixed this on my copy of zuck.js file by the definition below:

        zuck.remove = function(storyId) {
            var story = query('#' + id + ' > [data-id="' + storyId + '"]');
            story.parentNode.removeChild(story);
        };

**Comment by ramon82** [comment]
Thank's @nalsut, I really missed that code hahaha

I'll keep this issue open until I update the script. You can send me a PR if you want.
