### ISSUE TITLE
The demo site runs bad on iOS

### ISSUE THREAD

**Issue by LeoNatan** [ramon82/zuck.js#2]
Hi,

Cool project!
Here is my experience with the demo live site on my iPhone 7 Plus:

Bad scrolling (i.e. overflow not set to "touch"), animations are very choppy, videos do not play inline (no "playsinline"), unable to swipe to dismiss. The last one is not a big deal, but the others are crucial.

**Comment by ramon82** [comment]
Hey!

Thank you for your feedback, I'll fix those issues asap. Nice tip about overflow: touch, didn't know that :)

**Comment by LeoNatan** [comment]
Thank you for the fast reply!

**Comment by collinsnji** [comment]
I'm not so sure if the `overflow: touch` property is 100% supported yet :)
(Reference https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-overflow-scrolling)

Very cool project btw :+1:

**Comment by ramon82** [comment]
Thank you @collinsnji! About the overflow touch, I found out that it just makes scrolling feels natural on iOS. I though that @LeoNatan was referencing to use this on the carrousel, which was laggy.

Anyway, not anymore! I just updated the lib with the fix :)

**Comment by LeoNatan** [comment]
Much better, thanks!
