### ISSUE TITLE
Multiple story arrays on a single page

### ISSUE THREAD

**Issue by chadrob1990** [ramon82/zuck.js#20]
Trying to pull multiple arrays of stories to different divs on a single page. The first array of stories plays, but everything after that simply pulls up a grey screen. Doing some digging, it looks like there are multiple zuck modals being generated, but only one is being affected by the content.
![example zuck](https://user-images.githubusercontent.com/18753990/41636314-8ba1d2ae-7402-11e8-988f-b63aa884de25.png)
![stories2](https://user-images.githubusercontent.com/18753990/41636315-8ef5328e-7402-11e8-87dd-a06ca326497d.JPG)
![stories1](https://user-images.githubusercontent.com/18753990/41636318-90fa7652-7402-11e8-91d4-4767ff2f2c76.JPG)

**Comment by ramon82** [comment]
Hi,
I checked this and it's the script fault. I'll keep this issue open until I fix this.

Thanks

**Comment by shubhamchauhan** [comment]
Hey Ramon,
Any update on this issue?

**Comment by ramon82** [comment]
Fixed
