### ISSUE TITLE
Trying to make it dynamic using php in DRUPAL 7 

### ISSUE THREAD

**Issue by Mohva-kira** [ramon82/zuck.js#23]
zuck.js?pcdltd:893 Uncaught TypeError: Cannot read property 'parentNode' of undefined
    at playVideoItem (zuck.js?pcdltd:893)
    at createStoryViewer (zuck.js?pcdltd:503)
    at callback (zuck.js?pcdltd:704)
    at onOpen (zuck.js?pcdltd:227)
    at Object.show (zuck.js?pcdltd:751)
    at HTMLDivElement.story.onclick (zuck.js?pcdltd:857)

This is my code 
var stories = 
                                
                                        new Zuck('stories', {
					backNative: true,
					autoFullScreen: skins[skin]['autoFullScreen'],
					skin: skin,
					avatars: skins[skin]['avatars'],
					list: skins[skin]['list'],
					localStorage: true,
					stories: [
                                           
                                                    {
                                                        id: "<?php print $fields['nid']->content; ?>",
							photo: "<?php print $fields['field_influenceur']->content; ?>",
							name: "<?php print $fields['title']->content; ?>",
							link: "https://ramon.codes",
							lastUpdated: "<?php print $fields['changed']->content; ?>",
							
                                                            items: [
                                                       
								buildItem("<?php print $fields['title']->content; ?>-1", "photo", 3, "<?php print $fields['field_influenceur']->content; ?>", "https://pbs.twimg.com/media/C75V20SWsAAw5fO.jpg:small", '', false, "<?php print $fields['changed']->content; ?>"),
								buildItem("<?php print $fields['title']->content; ?>-2", "photo", 3, "<?php print $fields['field_influenceur_1']->content; ?>", "https://pbs.twimg.com/media/C7oA3btX0AE9hAx.jpg:small", 'https://ramon.codes', false, "<?php print $fields['changed']->content; ?>"),
								buildItem("<?php print $fields['title']->content; ?>-3", "video", 0, "<?php print $fields['field_video']->content; ?>", "https://pbs.twimg.com/media/C7oA3btX0AE9hAx.jpg:small", '', false, "<?php print $fields['changed']->content; ?>")
                                                                ]
                                                       
						
                                                    }<?php print ','; ?>
                                                    
					]
                                       
				});

**Comment by ramon82** [comment]
Hi, it seems that you have problem with escaping the strings on your code. Anyways, this is issue is not related with the script so i'm closing this thread.
