### ISSUE TITLE
Cannot read property 'querySelectorAll' of undefined at window.ZuckitaDaGalera.window.Zuck.q.addItem

### ISSUE THREAD

**Issue by InstantProgramming** [ramon82/zuck.js#27]
Hi guys , 
I'm using Zuck for a project, my backend is made with Laravel in php, and I use Vuejs in addition to laravel views for the FrontEnd. 

here is my Zuck vue component: 
```
<template>
    <div id="stories">
    </div>
</template>

<script>
    import "zuck.js/zuck.min";

    Date.prototype.getUnixTime = function() { return this.getTime()/1000|0 };
    if(!Date.now) Date.now = function() { return new Date(); };
    Date.time = function() { return Date.now().getUnixTime(); };

    export default {
        props: ['stories'],
        data() {
            return {
                orderedStories : []
            }
        },
        mounted (){
            let vm = this;
            for(let Story in vm.stories){
                    const escortId = vm.stories[Story].escort_id;
                    const escortName = vm.stories[Story].escort.user.name;
                    const escortAvatar = vm.stories[Story].escort.profile_picture?'/'+vm.stories[Story].escort.profile_picture.url:'/img/defaultAvatar.png';
                    const storyType = vm.stories[Story].type==="PIC"?"photo":"video";
                    const storyLength = storyType==="video"?0:10;
                    const storySrc = '/'+vm.stories[Story].upload.url;
                    const StoryTime = new Date(vm.stories[Story].updated_at).getUnixTime();
                    const StoryText = vm.stories[Story].text?vm.stories[Story].text:'';
                    const NewStoryItem = vm.buildItem(Story,storyType,storyLength,storySrc,storySrc,escortId,false, StoryTime, StoryText );
                    let alreadyStory= false;
                    vm.orderedStories.map(function (orderedStory) {
                        console.log(orderedStory)
                        if (orderedStory.id === escortId){
                            orderedStory.items.push(NewStoryItem);
                            if (orderedStory.lastUpdated>StoryTime) orderedStory.lastUpdated = StoryTime;
                            alreadyStory= true;
                        }
                    });
                    if (alreadyStory===false){
                        const newStory = {
                            id: parseInt(escortId),
                            photo: escortAvatar,
                            link:"/profile/"+escortId,
                            lastUpdated: StoryTime,
                            name: escortName,
                            items: [NewStoryItem]
                        };
                        vm.orderedStories.push(newStory)
                    }
            }
            this.initStories();
        },
        methods: {
            buildItem: function(id, type, length, src, preview, link, seen, time, linkText){
                return {
                    "id": parseInt(id),
                    "type": type,
                    "length": length,
                    "src": src,
                    "preview": preview,
                    "link": "/profile/"+link,
                    "linkText": linkText,
                    "seen": seen,
                    "time": time
                };
            },
            initStories: function(){
                let stories = new Zuck('stories', {
                    backNative: true,
                    autoFullScreen: false,
                    skin: 'Snapgram',
                    avatars: true,
                    list: false,
                    cubeEffect: true,
                    localStorage: true,
                    stories: this.orderedStories
                });
                document.body.style.display = 'block';
            }
        }
    }
</script>
```
When Mounted, the component take the stories and build items like Zuck need in the orderedStories array. (The process look if Story's owner already own a Story in the ordredStories array, if yes, it push the item, if not it creates the story and push the item !).
It looks first amazing in local, but when putted in production server and when there is more than 1 story, stories appears nice, but when click on them, it shows the story but with this error message : 
`app.js:137203 Uncaught TypeError: Cannot read property 'querySelectorAll' of undefined
    at window.ZuckitaDaGalera.window.Zuck.q.addItem (app.js:137203)
    at app.js:137203
    at t (app.js:137203)
    at window.ZuckitaDaGalera.window.Zuck.q.add.q.update (app.js:137203)
    at app.js:137203
    at t (app.js:137203)
    at k (app.js:137203)
    at T (app.js:137203)
    at onEnd (app.js:137203)
    at Object.next (app.js:137203)`

and then, story appears in a list and all is messed up (utill I clear localstorage, then stories appears again)

![capture](https://user-images.githubusercontent.com/188211/45263356-1f341a80-b428-11e8-9a2a-6f1388218b4a.PNG)
![capture1](https://user-images.githubusercontent.com/188211/45263357-1f341a80-b428-11e8-99d7-d13766c41663.PNG)

**Comment by InstantProgramming** [comment]
The issue is still here in production server only ...

**Comment by InstantProgramming** [comment]
I resolved the issue using 
"id": id + src
for the buildItem function to give stories a unique ID and now it seems to have no more confusion for the script and it works again in production. 

I will let the ticket open because still it's may be not my fault but script's and some others could have same issue, maybe it can be patched or explain in a better way in doc.

**Comment by ramon82** [comment]
Hey @InstantProgramming thanks for your feedback and your contribution. Currently I'm not having too much time to update this project, but I'll look into these issues more closely when I start working on this again :)
