### ISSUE TITLE
Back does not go to the previous person's story

### ISSUE THREAD

**Issue by ak2344** [ramon82/zuck.js#28]
Hello, when I am viewing a video/image and I hit back repeatedly, I go back to that person's first video/image.

From there if I continue hitting back, nothing happens, though I'd expect to view the previous person's stories.

Is this intentional? What would be involved in correcting it?

**Comment by ramon82** [comment]
Hi, 

Back button on Android devices or on the browser is supposed to close the story modal if "backNative" is true. The only way to navigate through stories is swiping or clicking on the sides of screen.
