### ISSUE TITLE
Stories come with an horizontal and vertical overflow

### ISSUE THREAD

**Issue by HamzaTalaghzi** [ramon82/zuck.js#29]
Hi!
The stories come with a horizontal and vertical overflow on the pages of a height greater than 100vh.
Tested on : 

> Chrome Version 70.0.3538.77 (Build officiel) (64 bits)

> Opera Version 56.0.3051.52

> Firefox Quantum 62.0.3

![image](https://user-images.githubusercontent.com/20133892/48038696-ae7c5680-e169-11e8-8e4d-73f073d25799.png)

**Comment by HamzaTalaghzi** [comment]
Thank you @Mustafaoeztuerk.
Concerning the overflow-y, I was  able to determine and fix the problem, but idk if this is the proper way to solve problem.
so to fix the problem i modified the zuck.js file by adding 2 lines:
```
line 342: document.body.style.overflow="auto";
line 880: document.body.style.overflow="hidden";
```
these lines comes after adding/removing "animated"

**Comment by HayotbekAbdulazizov** [comment]
Hello everybody has anyone used this plugin succesfully please help me i cannot use that i would be very grateful if you help me guys my-instagram instagram.com/hayotbekabdulazizov05
