### ISSUE TITLE
Uncaught (in promise) TypeError: Document not active

### ISSUE THREAD

**Issue by FKonyali** [ramon82/zuck.js#32]
Hi guys,

Even if Fullscreen mode is true or false, there is an error occurring in console; "Uncaught (in promise) TypeError: Document not active". As a result of my research I could not solve the problem. Can you help me? @ramon82

**Comment by ramon82** [comment]
Hi @FKonyali, 

I've tested here and I think the last version has some things broken. Currently I'm not having much time to update the script, so you can use an older version (which will be always be compatible) or wait for the next version...

Thanks for your feedback!
