### ISSUE TITLE
How to disable touch actions 

### ISSUE THREAD

**Issue by matteodem** [ramon82/zuck.js#36]
I need to disable the touch actions when viewing a story (e.g view next story, or previous) so that the custom element (in my case a button) is clicked and not the next story is viewed.

Any advice on how to go about that?

**Comment by ramon82** [comment]
You should modify the touchStart event to filter the tags you don't want to fire the touch event - currently it filters the < a > tag:

``` 
            if (event.target.nodeName === 'A') {
              return true;
            } else {
              event.preventDefault();
            }
```
