### ISSUE TITLE
How do I add left and right arrows?

### ISSUE THREAD

**Issue by FKonyali** [ramon82/zuck.js#37]
Hi,

I removed the "mousemove()" function to cancel the drag. I put the left and right arrows into the zuck.js. I've defined the setting called arrowControl.

`(option("arrowControl") ? '<div class="story-left"><i class="icon-arrow-back"></i></div>' : "")`
`(option("arrowControl") ? '<div class="story-right"><i class="icon-arrow-forward"></i></div>' : "")`

It's okay up here. I think click events will be done in the function named navigateItem. But I couldn't. 

When the left arrow is clicked, the slider has to go back. In the same way, the slider should go forward when the right arrow is clicked. Can you help me? @ramon82

Thank you.

**Comment by jnole** [comment]
Hi @FKonyali , 

I have the same issue, I think navigationItem event  is expecting coordinates, for this reason doesn't work. Hope @ramon82 can help us. 

Regards

**Comment by ramon82** [comment]
Hey,

There's an internal function called "moveStoryItem" which may help you https://github.com/ramon82/zuck.js/blob/master/src/zuck.js#L350

**Comment by FKonyali** [comment]
Hi,

With a few minor changes and additions, I had the look I wanted. I will share my actions as soon as possible. Thank you @ramon82

**Comment by trbsi** [comment]
@FKonyali 
Any luck?

**Comment by FKonyali** [comment]
Hi guys,

I'm sorry for the late reply. **Demo**: [Zuck.js Add the Previous and Next button](https://codepen.io/konyali/full/MxWaqZ)

I added to line 586. Line 542 and 547 line comment I did.

**What to do:**
- You need to add "arrowControl: true" to the plugin settings. The default value is true.
- You can add the appearance of arrows from line 436 in the js section. Css are up to you.

**Comment by trbsi** [comment]
@FKonyali that's awesome :D
Did you maybe manage to add arrows to this part: http://prntscr.com/mq2ty6

**Comment by MariyaPuzyr** [comment]
> @FKonyali that's awesome :D
> Did you maybe manage to add arrows to this part: http://prntscr.com/mq2ty6
> 
> @ramon82 can you add it to git?

Hello, did you add arrows to this part?

**Comment by FKonyali** [comment]
> Hello, did you add arrows to this part?

@MariyaPuzyr, yes I added arrow and draggable. I can share if you want

**Comment by MariyaPuzyr** [comment]
@FKonyali,

Oh, please. If you can. I'll be very grateful.

**Comment by netbee1136** [comment]
> 
> 
> Hi guys,
> 
> I'm sorry for the late reply. **Demo**: [Zuck.js Add the Previous and Next button](https://codepen.io/konyali/full/MxWaqZ)
> 
> I added to line 586. Line 542 and 547 line comment I did.
> 
> **What to do:**
> 
>     * You need to add "arrowControl: true" to the plugin settings. The default value is true.
> 
>     * You can add the appearance of arrows from line 436 in the js section. Css are up to you.
> 
> 
> @trbsi @jnole @ramon82

Wrong Guidance Dude 

from the master file there is a zuck.js-master\zuck.js-master\dist\zuck.mini,js using in the demo and there is nothing mentioned lines in that js file, can you pls guide us properly how to add the arrows ?
