### ISSUE TITLE
Syntax error: Unknown word (39:93) while importing zuck.css locally

### ISSUE THREAD

**Issue by ahmadbilalessensift** [ramon82/zuck.js#38]
I got an error while importing zuck.css from node_modules using `@import "~zuck.js/zuck.css";` in create-react-app . Here is the snippet of the code that I think produces the error : 

`#zuck-modal {
    outline: 0!important;
    overflow: hidden; 
    position: fixed;
    background: rgba(0, 0, 0, 0.75);
    0;
    z-index: 100000;
    font-size: 14px;
    font-family: inherit;
}`

Thank you.

**Comment by ramon82** [comment]
Hey, 
I think you should remove "!important" to make this work here

**Comment by ahmadbilalessensift** [comment]
I removed the `0;` before the z-index and it finally works, thanks

**Comment by ramon82** [comment]
Good catch, hahaha 

Pure CSS simply ignores errors like this... When I update the code I'll fix this typo too.
