### ISSUE TITLE
Close modal programatically

### ISSUE THREAD

**Issue by leiamac** [ramon82/zuck.js#39]
First of all, thank you for this plugin!

I'm using this in ionic 3, and as you say in the docs, backNative is set to false. I would like to implement the backNative functionality using ionic, but for that I need some function that I can trigger when the back button is pressed.

Is there a function to do that available or a way I can implement it?

**Comment by ramon82** [comment]
Hi,
Currently there's no public method to close the modal, but you can select the ```#zuck-modal``` element and then call ```el.close();```
