### ISSUE TITLE
Uncaught (in promise) DOMException: The play() request was interrupted by a call to pause().

### ISSUE THREAD

**Issue by leiamac** [ramon82/zuck.js#40]
It occurs on an Android app using Ionic 3.  After it happens, I'm unable to open the modal again.

The error log provided this link about the issue https://developers.google.com/web/updates/2017/06/play-request-was-interrupted

I tested it in another faster phone and the problem doesn't occur, I believe it is because the promise is resolved before the call to pause in that case.

**Comment by ramon82** [comment]
Hey @leiamac 
Thanks for the link, I didn't know that play() is a promise.. Gonna fix this issue on the next update
