### ISSUE TITLE
Videos on iOS play in full screen above the plugin ui

### ISSUE THREAD

**Issue by leiamac** [ramon82/zuck.js#41]
It happens in an Ionic 3 app using WKWebView.

Instead of playing inline, the video plays fullscreen and the controls are visible. If I swipe left or right or if I tap to go to the next slide it does nothing. I tried playing the demo page on safari and it works fine but not inside the app.

If you need more information please let me know.

**Comment by zyleee** [comment]
Had the same issue recently 

I am no iOS dev but it seems a webview config issue.

Try adding the “allowInlineMediaPlayback” config for the WebView:

let webConfiguration = WKWebViewConfiguration()
webConfiguration.allowsInlineMediaPlayback = true

**Comment by leiamac** [comment]
Yes! That was it, thank you @zyleee !
I had to add `<preference name="AllowInlineMediaPlayback" value="true" />` to config.xml and it worked.

**Comment by Dhananjay-EDU** [comment]
after adding <preference name="AllowInlineMediaPlayback" value="true" /> to config.xml worked for me.
