### ISSUE TITLE
How to Integrate with React.js

### ISSUE THREAD

**Issue by Ik-williams** [ramon82/zuck.js#44]
Hi. .
How to integrate with React.js

**Comment by Ik-williams** [comment]
lol i had to use react-insta-stories.

**Comment by ramon82** [comment]
¯\\_(ツ)_/¯

haha I don't work with React, so the best advice I have is to use the [alternate call](https://github.com/ramon82/zuck.js#alternate-call) as jsx then use the zuck.js api on your react logic...

**Comment by Ik-williams** [comment]
I tried doing that before. The issue is that the jsx when converted to pure react in the DOM makes using the zuck.js library div-id for stories impossible to integrate, because react components use a default div-id to render in the target html. So that's why im using react-insta-stories. Thanks for the reply @ramon82 !

**Comment by ramon82** [comment]
You can remove the id from html and pass the element reference on the init function.. But I don't know if zuck-modal works, maybe other html should be updated to JSX too

**Comment by Ik-williams** [comment]
my old instance i made in react was influenced by your zuck.js library. Im not using it anymore tho, because of too many user gestures like long press and mouse events are not very react-friendly to implement. 🙈. I have a new working story feature i made from scratch with react-insta-stories, lol and i also borrowed some code from your library. 🐥
@problem-solved thanks @ramon82

**Comment by rahulbansal16** [comment]
@Ik-williams Is the repository available to be used by the general public?
I was checking your repo but did not find it
