### ISSUE TITLE
Logo proposal 

### ISSUE THREAD

**Issue by jorlogicus** [ramon82/zuck.js#45]
Hello @ramon82 , today while exploring GitHub looking for interesting projects found yours and I would love to contribute by designing a logo for it since I'm a designer in development and an open source enthusiast. We would be working together to create the design that fits best. Of course it's totally free and you can quit whenever you want. In case you agree, please share any preferences you may have about colours, shapes, etc.

Kind regards.

**Comment by ramon82** [comment]
Hey @jorlogicus zuck.js already has an icon... Since it is part of the joke and some websites already posted it with the old logo, I didn't have interest to change it now. Thank you for the proposal!
