### ISSUE TITLE
Drag thumbnails on desktop with mouse or buttons (no touch), any setting opt ?

### ISSUE THREAD

**Issue by algrip** [ramon82/zuck.js#48]
Thanks Ramon! I couldn't dragcarousel thumbnails  with "mouse on desktop", is there the way, or to include arrow buttons? This case an additional code would be precious

**Comment by ramon82** [comment]
Hi @algrip 

Currently there's no method make a carousel on the story slider. Anyways, I think that it's not the main point of the library, since it's an separate ux component. I would suggest you to use some carousel lib to do this
