### ISSUE TITLE
Custom link to open stories

### ISSUE THREAD

**Issue by mt598** [ramon82/zuck.js#49]
I am working with zuck.js javascript library to show some stories on my website.

Instead of placing the avatar and the username on the website I prefer to integrate it as a link in my navigation. What's the best way to achieve this? 

Thanks for your help!

**Comment by ramon82** [comment]
Hi,
Currently there's no method to show the stories without the carousel, but you can hide the story carousel and mock the click event, like:

``` 
a.onclick = () => { 
let index = 0; // story user index
document.querySelectorAll('#stories .story')[index].click();
}
```

**Comment by dinacea93** [comment]
How choose/pointing to also specific sequence of story (and not only index story)?
