### ISSUE TITLE
Implementation in carousel

### ISSUE THREAD

**Issue by ArijitWeird** [ramon82/zuck.js#52]
Hi Ramon 
First of all thanks for this awesome library. I am planning to use it in one of my project. Since I didnt get good examples on web I am opening this ticket.
I have carousels in my project like this-->
		  <div class="owl-carousel">
		    <div class="item"><a href="#"><img src="img/home.jpg"></a></div>
		    <div class="item"><a href="#"><img src="img/home.jpg"></a></div>
		    <div class="item"><a href="#"><img src="img/home.jpg"></a></div>
		    <div class="item"><a href="#"><img src="img/home.jpg"></a></div>
		  </div>
		</div>
I want to implement stroies on each carousel. Can you briefly tell me if its possible ?
If so a liittle help or a small example is appreciable.
Thanks in  Advance

**Comment by ArijitWeird** [comment]
Hi Ramon
First of all thanks for this awesome library. I am planning to use it in one of my project. Since I didnt get good examples on web I am opening this ticket.
I have carousels in my project like this-->
`Hi Ramon
First of all thanks for this awesome library. I am planning to use it in one of my project. Since I didnt get good examples on web I am opening this ticket.
I have carousels in my project like this-->











I want to implement stroies on each carousel. Can you briefly tell me if its possible ?
If so a liittle help or a small example is appreciable.
Thanks in Advance`










I want to implement stroies on each carousel. Can you briefly tell me if its possible ?
If so a liittle help or a small example is appreciable.
Thanks in Advance

**Comment by ArijitWeird** [comment]
Hi Ramon
First of all thanks for this awesome library. I am planning to use it in one of my project. Since I didnt get good examples on web I am opening this ticket.
I have carousels in my project like this-->
`		  <div class="owl-carousel">
		    <div class="item"><a href="#"><img src="img/home.jpg"></a></div>
		    <div class="item"><a href="#"><img src="img/home.jpg"></a></div>
		    <div class="item"><a href="#"><img src="img/home.jpg"></a></div>
		    <div class="item"><a href="#"><img src="img/home.jpg"></a></div>
		  </div>
		</div>`

I want to implement stroies on each carousel. Can you briefly tell me if its possible ?
If so a liittle help or a small example is appreciable.
Thanks in Advance

**Comment by ramon82** [comment]
Hi @ArijitWeird,

Currently the only supported html format is the one generated by the script. Maybe in the next versions I could change that, but at this time I recommend you to use a json configuration.

**Comment by ArijitWeird** [comment]
Hi @ramon82 ,

Opening this issue again as I would like to know status for this. If  you are short of time , I can also help you with this. Just tell me how you are planning to implement this..

**Comment by ramon82** [comment]
Hey @ArijitWeird

Since zuck.js is my side project I didn't plan too much around this.. When I got time I just see what can be done then I start coding.

So, this feature needs a rewriting of code which I'm thinking to support React's JSX too. To be honest, I don't even know how to start that yet, but I think in a couple of weeks I can send an update like this. If you want to try in your own, I would start by changing all HTML templates on the JS file..
