### ISSUE TITLE
Story Item modal get out of screen when there are some context below story carousel

### ISSUE THREAD

**Issue by ArijitWeird** [ramon82/zuck.js#54]
Hi,
I am facing a strange glitch while implementing stories in my project. Story Item modal get out of screen when scroller is there to show some information beneath story div.

![story-modal](https://user-images.githubusercontent.com/31115145/60457236-221f2680-9c59-11e9-9603-b75b88cbb5a1.JPG)
![story-exmpl](https://user-images.githubusercontent.com/31115145/60457257-2e0ae880-9c59-11e9-9361-104d2e8b601c.JPG)

**Comment by ramon82** [comment]
Fixed on 1.5.0 version
