### ISSUE TITLE
Using custom elements

### ISSUE THREAD

**Issue by sezginriggs** [ramon82/zuck.js#55]
Hello,

Is it possible to use custom elements on images? Like adding button or any other html element? 

I found I could do it with onRender callback. But I'll be happy if it's possible to call Angular functions from the added elements like a button.

**Comment by ramon82** [comment]
Hi @sezginriggs 

Currently there's no support to include custom DOM elements, only custom html. You may edit the script around the following line to include custom functions after elements are created

https://github.com/ramon82/zuck.js/blob/3d6e993fe9783ad84d6f7a508afca67ef1bd7ecb/zuck.js#L437
