### ISSUE TITLE
Add custom action when click on link

### ISSUE THREAD

**Issue by rennerwins** [ramon82/zuck.js#57]
Is there a way to add custom action when click on link instead of redirect to a new page? 
I'm using this with Angular and want to do a routing with Angular router instead.

Thanks

**Comment by devsiodedra** [comment]
you need to paused slider and do whatever you need and then start slider.

**Comment by ramon82** [comment]
Hi,

You can manually add an event on ".link" inside story modal using onNavigateItem() callback or customize "viewerItemBody" template (since v1.5)
