### ISSUE TITLE
The buttons not work in Windows Chrome desktop and android mobile

### ISSUE THREAD

**Issue by jhpalen** [ramon82/zuck.js#61]
Hi there, 

This is a really good library for stories. One thing I notice though is that for our Shop Now buttons, they are not working in Chrome desktop and mobile. Lemme give you this as an example: http://feel22.com

And it is possible to insert Google Analytics code, right? To make sure that every click will fire an event to Google Analytics. I'd really appreciate your help, man. Thank you so much!

**Comment by ramon82** [comment]
Hi,

On this repo I will only respond questions about the library issues. If you have questions about custom implementations, consider buying some premium support via ko-fi (use the private message option with your e-mail). 

Btw you can use the callback options for Google Analytics events.

Thanks.
