### ISSUE TITLE
zuck js not working with nuxt.js

### ISSUE THREAD

**Issue by semihertugrul** [ramon82/zuck.js#65]
hi ramon.

I'm trying zuckjs my project but zuck js not working. I have github account and my project url : https://github.com/semihertugrul/zuckjs-nuxt

Especially you should look .....pages/index.vue page. What is the problem? 

Error :  Uncaught TypeError: timeline.setAttribute is not a function

is Zuckjs support nuxtjs? I'm waiting for information from you.
thanks for help

**Comment by ramon82** [comment]
Hi, 

You should use the ```reactive: true``` option when using the library with vue/react frameworks.

In nuxt/next or other backend libs, you must also include the html from generated stories, like the https://github.com/ramon82/zuck.js/blob/master/react.sample.html
