### ISSUE TITLE
Not getting the tap to go back

### ISSUE THREAD

**Issue by marbletravis** [ramon82/zuck.js#69]
See app here:

https://wardstories-2ae7e.web.app/

I have previousTap set to true, but it doesn't seem to be working like the demo, am I missing something? Do I have another setting that conflicts?

`
let zuck = new Zuck("stories", {
      skin: "snapgram",      // container class
      avatars: true,         // shows user photo instead of last story item preview
      list: false,           // displays a timeline instead of carousel
      openEffect: true,      // enables effect when opening story
      cubeEffect: true,     // enables the 3d cube effect when sliding story
      autoFullScreen: false, // enables fullscreen on mobile browsers
      backButton: true,      // adds a back button to close the story viewer
      backNative: false,     // uses window history to enable back button on browsers/android
      previousTap: true,     // use 1/3 of the screen to navigate to previous item when tap the story
      localStorage: true,    // set true to save "seen" position. Element must have a id to save properly.
    
      stories: stories,
`

**Comment by KocaHocTpa2** [comment]
@ramon82 
The error occurs because the direction constant is defined in the if block, and not at the beginning of the function.
``` 
  let touchEnd = function (event) {
          const storyViewer = query('#zuck-modal .viewing');
          const lastTouchOffset = touchOffset;

          if (touchOffset && !touchOffset.valid) {
            return;
          } else {
            if (delta) {
              const duration = touchOffset ? Date.now() - touchOffset.time : undefined;
              const isValid = (Number(duration) < 300 && Math.abs(delta.x) > 25) || Math.abs(delta.x) > modalContainer.slideWidth / 3;
              const direction = delta.x < 0; // declare out of if statement

              const index = direction ? query('#zuck-modal .story-viewer.next') : query('#zuck-modal .story-viewer.previous');
              const isOutOfBounds = (direction && !index) || (!direction && !index);
```

**Comment by ramon82** [comment]
Hey @KocaHocTpa2 it seems you're right! Just updated this on the new version. Thanks.

**Comment by marbletravis** [comment]
Thanks
