### ISSUE TITLE
Needs (more) React

### ISSUE THREAD

**Issue by hereinmybackyard** [ramon82/zuck.js#7]
Because this project was heavily inspired by Facebook, I think the project should have the whole user interface implemented by React.

React is a technology that Facebook heavily relies on, including their web and native applications.

**Comment by ramon82** [comment]
Hey! Vanilla JS team here :))

I guess that the script isn't hard to implement on React based apps, but my first idea was to build a simple stories plugin that can be integrated with everything. If i use React, it would be available for React users only.

Anyway, feel free to create a fork!
