### ISSUE TITLE
Please urgent Help Mr, Ramon

### ISSUE THREAD

**Issue by Marwenlouati0511** [ramon82/zuck.js#74]
Thanks a lot for you application it's very useful. I want from you two helps please.

**1)** when i put two video in the same story i face a problem after i close the story and return it back. The behavior that the last video get stuck.

**2)** I like how you make the night mode in you website. Please share the code.

If you want to understand better my problems, i share now a link from google drive that holds the 1) and the 2) helps.
https://drive.google.com/folderview?id=1-KK-A8KQoxo1gGMAd0_7T2OnNDyU2Lty

Thank you, i'll be very happy if you help me.

**Comment by Marwenlouati0511** [comment]
Also i want to get the real shape of picture and video because in zuck.js they will be a little bit bigger.

**Comment by ramon82** [comment]
1) The library was not designed to work with two videos on the same story. You should adapt it when using custom content.
2) Although I was thinking to open the code before, there are some problems about your request:
- This is not related with this project.
- There are already some libraries that do this. Find them.
3) The library supports all sizes of content and adjusts it on the screen automatically.
