### ISSUE TITLE
Can i use it in Vanilla javscript

### ISSUE THREAD

**Issue by Cusicon** [ramon82/zuck.js#77]
I saw the documentation here and on npm.
I just want to ask , Can i use it on pure js.
Because i feel like it is built solely for react. Why I felt so was because i saw react templating (jsx) in the html.

**Comment by ramon82** [comment]
Hello,

The project itself is made for Vanilla already. The React implementation is just an optional feature.

**Comment by mutethiaa** [comment]
Hello how can I use with php
