### ISSUE TITLE
onItemView

### ISSUE THREAD

**Issue by johann04** [ramon82/zuck.js#84]
It would be nice to have a callback for onItemView so I can write analytics every time an story item is viewed

**Comment by ramon82** [comment]
Did you read the documentation?

**Comment by johann04** [comment]
Yes, I did, you only have a "onView" callback, I would like to have a "onItemView" called on every item, not on every story.

**Comment by johann04** [comment]
did you read my request?

**Comment by ghost1254** [comment]
I am afraid, not.

**Comment by naman2202** [comment]
+++
@ramon82 
onView doesn't get triggered when a new item is loaded within the same story. Having this callback would be great.
