### ISSUE TITLE
I want to make the width of the zuck.js story item max 320px in resolutions on mobile

### ISSUE THREAD

**Issue by satiroglumustafa** [ramon82/zuck.js#86]
Hello to everyone. first of all thank you for this plugin.
I have a problem. I'm trying to make the story width max 320px at high resolutions from mobile. So I want it to be the same as on Instagram. how can I do that

**zuck.js image**: ![image](https://user-images.githubusercontent.com/11889057/83006823-74a8c480-a01b-11ea-82f3-4b461ba343e4.png)

**The image I want it to be**:
![image](https://user-images.githubusercontent.com/11889057/83006921-9609b080-a01b-11ea-98b3-44c474bed161.png)

So as a result, only the zuck.js story in 1920px is spreading full. I want to get the view on Instagram

**Comment by ramon82** [comment]
You can customize it by editing the src/styles/modal.css file

**Comment by satiroglumustafa** [comment]
I have the problem at this point, whatever I did and what it took, it took me hours. I couldn't do max 320px in desktop resolutions.
@ramon82
