### ISSUE TITLE
How to get new stories from database 

### ISSUE THREAD

**Issue by brainmuller77** [ramon82/zuck.js#88]
I want to know how I can make stories by retrieving database values added by user. 
Is there a way out.

**Comment by nastari** [comment]
You must make the values ​​read in the user's items part, be dynamic. When the user enters your website he makes a call to his backend / database and retrieves the values ​​that are generated. No different than that.

**Comment by brainmuller77** [comment]
Please I am using php as backend and I want it to be like users add stories by choosing from their gallery which will be loaded to the database that’s MySQL. Then I retrieve from database. Do you get me now please and how do I make the item part dynamic
