### ISSUE TITLE
How to hide lastUpdated?

### ISSUE THREAD

**Issue by cawa-93** [ramon82/zuck.js#91]
Your demo does not have time for the last change: https://ramon.codes/demo/zuck.js/index.html?skin=Snapssenger

![зображення](https://user-images.githubusercontent.com/1662812/89191010-f9c7d100-d5aa-11ea-9ec8-333860450552.png)

 I can't figure out how to hide the date & time. I tried to play your demo, and even so I still have dates & time.
https://jsfiddle.net/j80tgcLm/1/

![зображення](https://user-images.githubusercontent.com/1662812/89191047-06e4c000-d5ab-11ea-935b-53c54a256981.png)

**Comment by ar0ra1** [comment]
Css:

```
.time {
      display: none !important;
}
```
