### ISSUE TITLE
json problem

### ISSUE THREAD

**Issue by MohsenEs** [ramon82/zuck.js#94]
I use json but it does not show me where you think the problem is
[json.txt](https://github.com/ramon82/zuck.js/files/5084311/json.txt)

**Comment by ar0ra1** [comment]
use unix timestamp

**Comment by MohsenEs** [comment]
Thanks for the help, but where should I use it? Can you send me a sample code?

**Comment by MohsenEs** [comment]
> use unix timestamp
why?
