### ISSUE TITLE
no style 

### ISSUE THREAD

**Issue by dash7ou** [ramon82/zuck.js#97]
when I add it to my react project no style shows how can I show all styles?

**Comment by suathh** [comment]
Did you resolve this issue @dash7ou

**Comment by dash7ou** [comment]
yup you can copy the style in the dist folder or import it from nodemodule

**Comment by suathh** [comment]
Manually adding css file is worked for me too (Ionic-Angular project)

**Comment by NikosEfthias** [comment]
which css file @suathh there are like a billion css files in there

**Comment by suathh** [comment]
> which css file @suathh there are like a billion css files in there

you need to reference "node_modules/zuck.js/dist/zuck.min.css"
